### ISSUE TITLE
Add pre-built win32 executables as releases

### ISSUE THREAD

**Issue by touyudexiaomao** [jattach/jattach#79]
Building stuff (especially in Windows) can be a PITA, so pre-built executables would be greatly appreciated.

I found that there was a period of win32 release in the middle. But unfortunately it was not provided in the latest release.

If a release version of win32 could be provided, it would be greatly appreciated.

**Comment by apangin** [comment]
> Building stuff (especially in Windows) can be a PITA

It's true. Furthermore, in order to publish a new release, project maintainers not only need to build binaries, but also to test them with different versions of JDK on different Windows versions in different configurations, then take additional steps to ensure binaries are not blocked by SmartScreen etc. Given high maintenance overhead and low popularity of 32-bit Java on Windows, we decided to discontinue providing 32-bit builds of `jattach`.

You may still build binaries yourself. As mentioned above, it's not the biggest problem. In fact, it's just a matter of a single command (assuming MSVC environment variables are set), e.g.
```
cl.exe /O2 /D_CRT_SECURE_NO_WARNINGS /DJATTACH_VERSION=\"2.2\" /Fobuild/jattach.obj /Febuild/jattach32.exe src/windows/jattach.c advapi32.lib /link /SUBSYSTEM:CONSOLE,5.02
```

Alternatively, you may take one of the previous 32-bit builds.
The last one is from the [release 2.1](https://github.com/jattach/jattach/releases/tag/v2.1) - there were not too many changes since then.

**Comment by touyudexiaomao** [comment]
Thank you very much for your reply.
I will try to compile using the above command.
